/** Bancos brasileiros (código COMPE) para seleção no cadastro de funcionários. */
export interface BrazilianBank {
  code: string;
  name: string;
}

export const BRAZILIAN_BANKS: BrazilianBank[] = [
  { code: '001', name: 'Banco do Brasil S.A.' },
  { code: '003', name: 'Banco da Amazônia S.A.' },
  { code: '004', name: 'Banco do Nordeste do Brasil S.A.' },
  { code: '007', name: 'Banco Nacional de Desenvolvimento Econômico e Social – BNDES' },
  { code: '010', name: 'Credicoamo Crédito Rural Cooperativa' },
  { code: '011', name: 'Credit Suisse Hedging-Griffo Corretora de Valores S.A.' },
  { code: '012', name: 'Banco Inbursa S.A.' },
  { code: '014', name: 'State Street Brasil S.A. – Banco Comercial' },
  { code: '015', name: 'UBS Brasil Corretora de Câmbio, Títulos e Valores Mobiliários S.A.' },
  { code: '016', name: 'Cooperativa de Crédito Mútuo dos Despachantes de Trânsito de Santa Catarina e Rio Grande do Sul' },
  { code: '017', name: 'BNY Mellon Banco S.A.' },
  { code: '018', name: 'Banco Tricury S.A.' },
  { code: '021', name: 'Banestes S.A. Banco do Estado do Espírito Santo' },
  { code: '024', name: 'Banco Bandepe S.A.' },
  { code: '025', name: 'Banco Alfa S.A.' },
  { code: '029', name: 'Banco Itaú Consignado S.A.' },
  { code: '033', name: 'Banco Santander (Brasil) S.A.' },
  { code: '036', name: 'Banco Bradesco BBI S.A.' },
  { code: '037', name: 'Banco do Estado do Pará S.A.' },
  { code: '040', name: 'Banco Cargill S.A.' },
  { code: '041', name: 'Banrisul – Banco do Estado do Rio Grande do Sul S.A.' },
  { code: '047', name: 'Banco do Estado de Sergipe S.A.' },
  { code: '060', name: 'Confidence Corretora de Câmbio S.A.' },
  { code: '062', name: 'Hipercard Banco Múltiplo S.A.' },
  { code: '063', name: 'Banco Bradescard S.A.' },
  { code: '064', name: 'Goldman Sachs do Brasil Banco Múltiplo S.A.' },
  { code: '065', name: 'Banco AndBank (Brasil) S.A.' },
  { code: '066', name: 'Banco Morgan Stanley S.A.' },
  { code: '069', name: 'Banco Crefisa S.A.' },
  { code: '070', name: 'Banco de Brasília S.A. (BRB)' },
  { code: '074', name: 'Banco J. Safra S.A.' },
  { code: '075', name: 'Banco ABN Amro S.A.' },
  { code: '076', name: 'Banco KDB do Brasil S.A.' },
  { code: '077', name: 'Banco Inter S.A.' },
  { code: '078', name: 'Haitong Banco de Investimento do Brasil S.A.' },
  { code: '079', name: 'Banco Original do Agronegócio S.A.' },
  { code: '080', name: 'BT Corretora de Câmbio Ltda.' },
  { code: '081', name: 'BancoSeguro S.A.' },
  { code: '082', name: 'Banco Topázio S.A.' },
  { code: '083', name: 'Banco da China Brasil S.A.' },
  { code: '084', name: 'Uniprime Norte do Paraná – Cooperativa de Crédito Ltda.' },
  { code: '085', name: 'Cooperativa Central de Crédito – Ailos' },
  { code: '088', name: 'Banco Randon S.A.' },
  { code: '089', name: 'Credisan Cooperativa de Crédito' },
  { code: '091', name: 'Central de Cooperativas de Economia e Crédito Mútuo do Estado do Rio Grande do Sul – Unicred' },
  { code: '092', name: 'Brickell S.A. Crédito, Financiamento e Investimento' },
  { code: '093', name: 'PóloCred Sociedade de Crédito ao Microempreendedor e à Empresa de Pequeno Porte' },
  { code: '094', name: 'Banco Finaxis S.A.' },
  { code: '095', name: 'Travelex Banco de Câmbio S.A.' },
  { code: '096', name: 'Banco B3 S.A.' },
  { code: '097', name: 'Credisis – Central de Cooperativas de Crédito Ltda.' },
  { code: '098', name: 'Credialiança Cooperativa de Crédito Rural' },
  { code: '099', name: 'Uniprime Central – Central Interestadual de Cooperativas de Crédito Ltda.' },
  { code: '100', name: 'Planner Corretora de Valores S.A.' },
  { code: '101', name: 'Renascença Distribuidora de Títulos e Valores Mobiliários Ltda.' },
  { code: '102', name: 'XP Investimentos Corretora de Câmbio Títulos e Valores Mobiliários S.A.' },
  { code: '104', name: 'Caixa Econômica Federal' },
  { code: '105', name: 'Lecca Crédito, Financiamento e Investimento S.A.' },
  { code: '107', name: 'Banco Bocom BBM S.A.' },
  { code: '111', name: 'Oliveira Trust Distribuidora de Títulos e Valores Mobiliários S.A.' },
  { code: '113', name: 'Magliano S.A. Corretora de Cambio e Valores Mobiliarios' },
  { code: '114', name: 'Central Cooperativa de Crédito no Estado do Espírito Santo – CECOOP' },
  { code: '117', name: 'Advanced Corretora de Câmbio Ltda.' },
  { code: '119', name: 'Banco Western Union do Brasil S.A.' },
  { code: '120', name: 'Banco Rodobens S.A.' },
  { code: '121', name: 'Banco Agibank S.A.' },
  { code: '122', name: 'Banco Bradesco BERJ S.A.' },
  { code: '124', name: 'Banco Woori Bank do Brasil S.A.' },
  { code: '125', name: 'Banco Genial S.A.' },
  { code: '126', name: 'BR Partners Banco de Investimento S.A.' },
  { code: '127', name: 'Codepe Corretora de Valores e Câmbio S.A.' },
  { code: '128', name: 'MS Bank S.A. Banco de Câmbio' },
  { code: '129', name: 'UBS Brasil Banco de Investimento S.A.' },
  { code: '130', name: 'Caruana S.A. Sociedade de Crédito, Financiamento e Investimento' },
  { code: '131', name: 'Tullett Prebon Brasil Corretora de Valores e Câmbio Ltda.' },
  { code: '132', name: 'ICBC do Brasil Banco Múltiplo S.A.' },
  { code: '133', name: 'Confederação Nacional das Cooperativas Centrais de Crédito e Economia Familiar e Solidária – Cresol' },
  { code: '134', name: 'BGC Liquidez Distribuidora de Títulos e Valores Mobiliários Ltda.' },
  { code: '136', name: 'Confederação Nacional das Cooperativas Centrais Unicred Ltda. – Unicred do Brasil' },
  { code: '137', name: 'Multimoney Corretora de Câmbio Ltda.' },
  { code: '138', name: 'Get Money Corretora de Câmbio S.A.' },
  { code: '139', name: 'Intesa Sanpaolo Brasil S.A. – Banco Múltiplo' },
  { code: '140', name: 'Easynvest – Título Corretora de Valores SA' },
  { code: '142', name: 'Broker Brasil Corretora de Câmbio Ltda.' },
  { code: '143', name: 'Treviso Corretora de Câmbio S.A.' },
  { code: '144', name: 'Bexs Banco de Câmbio S.A.' },
  { code: '145', name: 'Levycam Corretora de Câmbio e Valores Ltda.' },
  { code: '146', name: 'Guitta Corretora de Câmbio Ltda.' },
  { code: '149', name: 'Facta Financeira S.A. Crédito, Financiamento e Investimento' },
  { code: '157', name: 'ICAP do Brasil Corretora de Títulos e Valores Mobiliários Ltda.' },
  { code: '159', name: 'Casa do Crédito S.A. Sociedade de Crédito ao Microempreendedor' },
  { code: '163', name: 'Commerzbank Brasil S.A. – Banco Múltiplo' },
  { code: '169', name: 'Banco Olé Bonsucesso Consignado S.A.' },
  { code: '172', name: 'Albatross Corretora de Câmbio e Valores S.A.' },
  { code: '173', name: 'BRL Trust Distribuidora de Títulos e Valores Mobiliários S.A.' },
  { code: '174', name: 'Pefisa S.A. Crédito, Financiamento e Investimento' },
  { code: '177', name: 'Guide Investimentos S.A. Corretora de Valores' },
  { code: '180', name: 'CM Capital Markets Corretora de Câmbio, Títulos e Valores Mobiliários Ltda.' },
  { code: '183', name: 'Socred S.A. Sociedade de Crédito ao Microempreendedor e à Empresa de Pequeno Porte' },
  { code: '184', name: 'Banco Itaú BBA S.A.' },
  { code: '188', name: 'Ativa Investimentos S.A. Corretora de Títulos Câmbio e Valores' },
  { code: '189', name: 'HS Financeira S.A. Crédito, Financiamento e Investimentos' },
  { code: '190', name: 'Servicoop – Cooperativa de Economia e Crédito Mútuo dos Servidores Públicos do Estado de São Paulo' },
  { code: '191', name: 'Nova Futura Corretora de Títulos e Valores Mobiliários Ltda.' },
  { code: '194', name: 'Parmetal Distribuidora de Títulos e Valores Mobiliários Ltda.' },
  { code: '196', name: 'Fair Corretora de Câmbio S.A.' },
  { code: '197', name: 'Stone Instituição de Pagamento S.A.' },
  { code: '208', name: 'Banco BTG Pactual S.A.' },
  { code: '212', name: 'Banco Original S.A.' },
  { code: '213', name: 'Banco Arbi S.A.' },
  { code: '217', name: 'Banco John Deere S.A.' },
  { code: '218', name: 'Banco BS2 S.A.' },
  { code: '222', name: 'Banco Credit Agricole Brasil S.A.' },
  { code: '224', name: 'Banco Fibra S.A.' },
  { code: '233', name: 'Banco Cifra S.A.' },
  { code: '237', name: 'Banco Bradesco S.A.' },
  { code: '241', name: 'Banco Clássico S.A.' },
  { code: '243', name: 'Banco Master S.A.' },
  { code: '246', name: 'Banco ABC Brasil S.A.' },
  { code: '249', name: 'Banco Investcred Unibanco S.A.' },
  { code: '250', name: 'BCV – Banco de Crédito e Varejo S.A.' },
  { code: '253', name: 'Bexs Corretora de Câmbio S.A.' },
  { code: '254', name: 'Paraná Banco S.A.' },
  { code: '259', name: 'Moneycorp Banco de Câmbio S.A.' },
  { code: '260', name: 'Nu Pagamentos S.A. (Nubank)' },
  { code: '265', name: 'Banco Fator S.A.' },
  { code: '266', name: 'Banco Cédula S.A.' },
  { code: '268', name: 'Bari Companhia Hipotecária' },
  { code: '269', name: 'HSBC Brasil S.A. Banco de Investimento' },
  { code: '270', name: 'Sagitur Corretora de Câmbio Ltda.' },
  { code: '271', name: 'IB Corretora de Câmbio, Títulos e Valores Mobiliários Ltda.' },
  { code: '272', name: 'AGK Corretora de Câmbio S.A.' },
  { code: '273', name: 'Cooperativa de Crédito Rural de São Miguel do Oeste – Sulcredi/São Miguel' },
  { code: '274', name: 'Money Plus Sociedade de Crédito ao Microempreendedor e à Empresa de Pequeno Porte' },
  { code: '276', name: 'Banco Senff S.A.' },
  { code: '278', name: 'Genial Investimentos Corretora de Valores Mobiliários S.A.' },
  { code: '279', name: 'Cooperativa de Crédito Rural de Primavera do Leste' },
  { code: '280', name: 'Avista S.A. Crédito, Financiamento e Investimento' },
  { code: '281', name: 'Cooperativa de Crédito Rural Coopavel' },
  { code: '283', name: 'RB Capital Investimentos Distribuidora de Títulos e Valores Mobiliários Ltda.' },
  { code: '285', name: 'Frente Corretora de Câmbio Ltda.' },
  { code: '286', name: 'Cooperativa de Crédito Rural de De São Miguel do Oeste – Sulcredi/Oeste' },
  { code: '288', name: 'Carol Distribuidora de Títulos e Valores Mobiliários Ltda.' },
  { code: '289', name: 'DECYSEO Corretora de Cambio Ltda.' },
  { code: '290', name: 'PagSeguro Internet S.A. (PagBank)' },
  { code: '292', name: 'BS2 Distribuidora de Títulos e Valores Mobiliários S.A.' },
  { code: '293', name: 'Lastro RDV Distribuidora de Títulos e Valores Mobiliários Ltda.' },
  { code: '296', name: 'Vision Corretora de Câmbio Ltda.' },
  { code: '298', name: 'Vip’s Corretora de Câmbio Ltda.' },
  { code: '299', name: 'Banco Afinz S.A. Banco Múltiplo' },
  { code: '300', name: 'Banco La Nacion Argentina' },
  { code: '301', name: 'BPP Instituição de Pagamento S.A.' },
  { code: '306', name: 'Portopar Distribuidora de Títulos e Valores Mobiliários Ltda.' },
  { code: '307', name: 'Terra Investimentos Distribuidora de Títulos e Valores Mobiliários Ltda.' },
  { code: '309', name: 'Cambionet Corretora de Câmbio Ltda.' },
  { code: '310', name: 'VORTX Distribuidora de Títulos e Valores Mobiliários Ltda.' },
  { code: '311', name: 'Dourama Corretora de Câmbio Ltda.' },
  { code: '312', name: 'HSCM – Sociedade de Crédito ao Microempreendedor e à Empresa de Pequeno Porte Ltda.' },
  { code: '313', name: 'Amazônia Corretora de Câmbio Ltda.' },
  { code: '315', name: 'PI Distribuidora de Títulos e Valores Mobiliários S.A.' },
  { code: '318', name: 'Banco BMG S.A.' },
  { code: '319', name: 'OM Distribuidora de Títulos e Valores Mobiliários Ltda.' },
  { code: '320', name: 'China Construction Bank (Brasil) Banco Múltiplo S.A.' },
  { code: '321', name: 'Crefaz Sociedade de Crédito ao Microempreendedor e à Empresa de Pequeno Porte Ltda.' },
  { code: '322', name: 'Cooperativa de Crédito Rural de Abelardo Luz – Sulcredi/Crediluz' },
  { code: '323', name: 'Mercado Pago Instituição de Pagamento Ltda.' },
  { code: '324', name: 'Cartos Sociedade de Crédito Direto S.A.' },
  { code: '325', name: 'Órama Distribuidora de Títulos e Valores Mobiliários S.A.' },
  { code: '326', name: 'Parati – Crédito, Financiamento e Investimento S.A.' },
  { code: '328', name: 'Cooperativa de Economia e Crédito Mútuo dos Fabricantes de Calçados de Franca' },
  { code: '329', name: 'QI Sociedade de Crédito Direto S.A.' },
  { code: '330', name: 'Banco Bari de Investimentos e Financiamentos S.A.' },
  { code: '331', name: 'Fram Capital Distribuidora de Títulos e Valores Mobiliários S.A.' },
  { code: '332', name: 'Acesso Soluções de Pagamento S.A.' },
  { code: '335', name: 'Banco Digio S.A.' },
  { code: '336', name: 'Banco C6 S.A.' },
  { code: '340', name: 'Super Pagamentos e Administração de Meios Eletrônicos S.A.' },
  { code: '341', name: 'Itaú Unibanco S.A.' },
  { code: '342', name: 'Creditas Sociedade de Crédito Direto S.A.' },
  { code: '343', name: 'FFA Sociedade de Crédito ao Microempreendedor e à Empresa de Pequeno Porte Ltda.' },
  { code: '348', name: 'Banco XP S.A.' },
  { code: '349', name: 'AL5 S.A. Crédito, Financiamento e Investimento' },
  { code: '350', name: 'Cooperativa De Crédito Rural De Pequenos Agricultores E Da Reforma Agrária Do Centro Oeste Do Paraná' },
  { code: '352', name: 'Toro Corretora de Títulos e Valores Mobiliários Ltda.' },
  { code: '354', name: 'Necton Investimentos S.A. Corretora de Valores Mobiliários e Commodities' },
  { code: '355', name: 'Ótimo Sociedade de Crédito Direto S.A.' },
  { code: '358', name: 'Midway S.A. – Crédito, Financiamento e Investimento' },
  { code: '359', name: 'Zema Crédito, Financiamento e Investimento S.A.' },
  { code: '360', name: 'Trinus Capital Distribuidora de Títulos e Valores Mobiliários S.A.' },
  { code: '362', name: 'Cielo S.A.' },
  { code: '363', name: 'Socopa Sociedade Corretora Paulista S.A.' },
  { code: '364', name: 'Gerencianet Instituição de Pagamento S.A. (Efí)' },
  { code: '365', name: 'Solidus S.A. Corretora de Cambio e Valores Mobiliarios' },
  { code: '366', name: 'Banco Société Générale Brasil S.A.' },
  { code: '367', name: 'Vitreo Distribuidora de Títulos e Valores Mobiliários S.A.' },
  { code: '368', name: 'Banco CSF S.A.' },
  { code: '370', name: 'Banco Mizuho do Brasil S.A.' },
  { code: '371', name: 'Warren Corretora de Valores Mobiliários e Câmbio Ltda.' },
  { code: '373', name: 'UP.P Sociedade de Empréstimo Entre Pessoas S.A.' },
  { code: '374', name: 'Realize Crédito, Financiamento e Investimento S.A.' },
  { code: '376', name: 'Banco J.P. Morgan S.A.' },
  { code: '377', name: 'BMS Sociedade de Crédito Direto S.A.' },
  { code: '378', name: 'Banco Brasileiro de Crédito S.A.' },
  { code: '379', name: 'Cooperforte – Cooperativa de Economia e Crédito Mútuo de Funcionários de Instituições Financeiras Públicas Federais Ltda.' },
  { code: '380', name: 'PicPay Instituição de Pagamento S.A.' },
  { code: '381', name: 'Banco Mercedes-Benz do Brasil S.A.' },
  { code: '382', name: 'Fidúcia Sociedade de Crédito ao Microempreendedor e à Empresa de Pequeno Porte Ltda.' },
  { code: '383', name: 'Juno Instituição de Pagamento Ltda. (BoletoBancário.com)' },
  { code: '384', name: 'Global Financiamentos e Investimentos S.A. – Crédito, Financiamento e Investimento' },
  { code: '385', name: 'Cooperativa de Economia e Crédito Mútuo dos Trabalhadores Portuários da Grande Vitória – CECM' },
  { code: '386', name: 'Nu Financeira S.A. Sociedade de Crédito, Financiamento e Investimento' },
  { code: '387', name: 'Banco Toyota do Brasil S.A.' },
  { code: '389', name: 'Banco Mercantil do Brasil S.A.' },
  { code: '390', name: 'Banco GM S.A.' },
  { code: '391', name: 'Cooperativa de Crédito Rural de Ibiam – Sulcredi/Ibiam' },
  { code: '393', name: 'Banco Volkswagen S.A.' },
  { code: '394', name: 'Banco Bradesco Financiamentos S.A.' },
  { code: '395', name: 'F.D’Gold – Distribuidora de Títulos e Valores Mobiliários Ltda.' },
  { code: '396', name: 'Hub Instituição de Pagamento S.A.' },
  { code: '397', name: 'Listo Sociedade de Crédito Direto S.A.' },
  { code: '398', name: 'Ideal Corretora de Títulos e Valores Mobiliários S.A.' },
  { code: '399', name: 'Kirton Bank S.A. – Banco Múltiplo' },
  { code: '400', name: 'Cooperativa de Crédito, Poupança e Serviços Financeiros' },
  { code: '401', name: 'IUGU Instituição de Pagamento S.A.' },
  { code: '402', name: 'Cobuccio Sociedade de Crédito Direto S.A.' },
  { code: '403', name: 'Cora Sociedade de Crédito Direto S.A.' },
  { code: '404', name: 'SumUp Sociedade de Crédito Direto S.A.' },
  { code: '406', name: 'Accredito – Sociedade de Crédito Direto S.A.' },
  { code: '407', name: 'Índigo Investimentos Distribuidora de Títulos e Valores Mobiliários Ltda.' },
  { code: '408', name: 'Bônuscred Sociedade de Crédito Direto S.A.' },
  { code: '410', name: 'Planner Sociedade de Crédito Direto S.A.' },
  { code: '411', name: 'Via Certa Financiadora S.A. – Crédito, Financiamento e Investimentos' },
  { code: '412', name: 'Social Bank Banco Múltiplo S.A.' },
  { code: '413', name: 'Banco BV S.A.' },
  { code: '414', name: 'Lend Sociedade de Crédito Direto S.A.' },
  { code: '416', name: 'Lamara Sociedade de Crédito Direto S.A.' },
  { code: '418', name: 'Zipdin Soluções Digitais Sociedade de Crédito Direto S.A.' },
  { code: '419', name: 'Numbrs Sociedade de Crédito Direto S.A.' },
  { code: '421', name: 'Lar Cooperativa de Crédito – Lar Credi' },
  { code: '422', name: 'Banco Safra S.A.' },
  { code: '423', name: 'Coluna S.A. Distribuidora de Títulos e Valores Mobiliários' },
  { code: '425', name: 'Socinal S.A. – Crédito, Financiamento e Investimento' },
  { code: '426', name: 'Biorc Financeira – Crédito, Financiamento e Investimento S.A.' },
  { code: '427', name: 'Cooperativa de Crédito dos Servidores da Universidade Federal do Espírito Santo – Cred-UFES' },
  { code: '428', name: 'Credsystem Sociedade de Crédito Direto S.A.' },
  { code: '429', name: 'Crediare Sociedade de Crédito Direto S.A.' },
  { code: '430', name: 'Cooperativa de Economia e Crédito Mútuo da Associação dos Funcionários Públicos do Município de São Paulo' },
  { code: '433', name: 'BR Partners Banco de Investimento S.A.' },
  { code: '435', name: 'Delcred Sociedade de Crédito Direto S.A.' },
  { code: '438', name: 'Planner Trustee Distribuidora de Títulos e Valores Mobiliários Ltda.' },
  { code: '439', name: 'ID Corretora de Títulos e Valores Mobiliários S.A.' },
  { code: '440', name: 'Credibem Sociedade de Crédito Direto S.A.' },
  { code: '442', name: 'Magnetis Distribuidora de Títulos e Valores Mobiliários Ltda.' },
  { code: '443', name: 'Credisfera Sociedade de Crédito Direto S.A.' },
  { code: '444', name: 'Trinus Sociedade de Crédito Direto S.A.' },
  { code: '445', name: 'Plantae Credito, Financiamento e Investimento S.A.' },
  { code: '447', name: 'Miravex Sociedade de Crédito Direto S.A.' },
  { code: '448', name: 'Hemera Distribuidora de Títulos e Valores Mobiliários Ltda.' },
  { code: '449', name: 'DM Financeira S.A. – Crédito, Financiamento e Investimento' },
  { code: '450', name: 'FitBank Pagamentos Eletrônicos S.A.' },
  { code: '451', name: 'J17 – Sociedade de Crédito Direto S.A.' },
  { code: '452', name: 'Credifit Sociedade de Crédito Direto S.A.' },
  { code: '454', name: 'Mérito Distribuidora de Títulos e Valores Mobiliários Ltda.' },
  { code: '455', name: 'Fênix Distribuidora de Títulos e Valores Mobiliários Ltda.' },
  { code: '456', name: 'Banco MUFG Brasil S.A.' },
  { code: '457', name: 'UY3 Sociedade de Crédito Direto S.A.' },
  { code: '458', name: 'Hedge Investments Distribuidora de Títulos e Valores Mobiliários Ltda.' },
  { code: '459', name: 'CCM Serviços Aéreos Credito Mutuo' },
  { code: '460', name: 'Unavanti Sociedade de Crédito Direto S.A.' },
  { code: '461', name: 'Asaas Gestão Financeira Instituição de Pagamento S.A.' },
  { code: '462', name: 'Stark Sociedade de Crédito Direto S.A.' },
  { code: '464', name: 'Banco Sumitomo Mitsui Brasileiro S.A.' },
  { code: '465', name: 'Capital Consig Sociedade de Crédito Direto S.A.' },
  { code: '467', name: 'Master S.A. Corretora de Câmbio, Títulos e Valores Mobiliários' },
  { code: '468', name: 'Portocred Sociedade de Crédito Direto S.A.' },
  { code: '469', name: 'PicPay Corretora de Valores S.A.' },
  { code: '470', name: 'CDC Sociedade de Crédito Direto S.A.' },
  { code: '471', name: 'Cooperativa de Economia e Crédito Mútuo dos Servidores Públicos Municipais do Vale do Rio São Lourenço' },
  { code: '473', name: 'Banco Caixa Geral – Brasil S.A.' },
  { code: '475', name: 'Banco Yamaha Motor do Brasil S.A.' },
  { code: '477', name: 'Citibank N.A.' },
  { code: '478', name: 'Gazincred Sociedade de Crédito, Financiamento e Investimento S.A.' },
  { code: '479', name: 'Banco ItaúBank S.A.' },
  { code: '481', name: 'Superlógica Sociedade de Crédito Direto S.A.' },
  { code: '482', name: 'SBCASH Sociedade de Crédito Direto S.A.' },
  { code: '484', name: 'Banco Keb Hana do Brasil S.A.' },
  { code: '487', name: 'Deutsche Bank S.A. Banco Alemão' },
  { code: '488', name: 'JPMorgan Chase Bank, National Association' },
  { code: '495', name: 'Banco de La Provincia de Buenos Aires' },
  { code: '505', name: 'Banco Credit Suisse (Brasil) S.A.' },
  { code: '507', name: 'Sociedade Educacional Brasileira S.A. – Crédito, Financiamento e Investimento' },
  { code: '509', name: 'Celcoin Instituição de Pagamento S.A.' },
  { code: '511', name: 'Magnum Sociedade de Crédito Direto S.A.' },
  { code: '512', name: 'Finansinos Sociedade de Crédito, Financiamento e Investimento S.A.' },
  { code: '513', name: 'Atlântico Sociedade de Crédito Direto S.A.' },
  { code: '516', name: 'QESH Instituição de Pagamento S.A.' },
  { code: '518', name: 'Mercado Crédito Sociedade de Crédito, Financiamento e Investimento S.A.' },
  { code: '519', name: 'Sparta Sociedade de Crédito Direto S.A.' },
  { code: '523', name: 'HR Digital Sociedade de Crédito Direto S.A.' },
  { code: '526', name: 'Montebravo Investimentos – Distribuidora de Títulos e Valores Mobiliários Ltda.' },
  { code: '529', name: 'Pinbank Brasil Instituição de Pagamento S.A.' },
  { code: '530', name: 'Ser Finance Sociedade de Crédito Direto S.A.' },
  { code: '531', name: 'BMP Money Plus Sociedade de Crédito ao Microempreendedor e à Empresa de Pequeno Porte' },
  { code: '535', name: 'Orca Distribuidora de Títulos e Valores Mobiliários Ltda.' },
  { code: '536', name: 'Neon Financeira – Crédito, Financiamento e Investimento S.A.' },
  { code: '537', name: 'Microcash Sociedade de Crédito ao Microempreendedor e à Empresa de Pequeno Porte' },
  { code: '541', name: 'Fundação Dom Cabral – Sociedade de Crédito Direto S.A.' },
  { code: '545', name: 'Senso Corretora de Câmbio e Valores Mobiliários S.A.' },
  { code: '546', name: 'U4C Instituição de Pagamento S.A.' },
  { code: '600', name: 'Banco Luso Brasileiro S.A.' },
  { code: '604', name: 'Banco Industrial do Brasil S.A.' },
  { code: '610', name: 'Banco VR S.A.' },
  { code: '611', name: 'Banco Paulista S.A.' },
  { code: '612', name: 'Banco Guanabara S.A.' },
  { code: '613', name: 'Omni Banco S.A.' },
  { code: '623', name: 'Banco Pan S.A.' },
  { code: '626', name: 'Banco CCB Brasil S.A.' },
  { code: '630', name: 'Banco Smartbank S.A.' },
  { code: '633', name: 'Banco Rendimento S.A.' },
  { code: '634', name: 'Banco Triângulo S.A.' },
  { code: '637', name: 'Banco Sofisa S.A.' },
  { code: '643', name: 'Banco Pine S.A.' },
  { code: '652', name: 'Itaú Unibanco Holding S.A.' },
  { code: '653', name: 'Banco Voiter S.A.' },
  { code: '654', name: 'Banco Digimais S.A.' },
  { code: '655', name: 'Banco Votorantim S.A.' },
  { code: '707', name: 'Banco Daycoval S.A.' },
  { code: '712', name: 'Banco Ourinvest S.A.' },
  { code: '720', name: 'Banco RNX S.A.' },
  { code: '739', name: 'Banco Cetelem S.A.' },
  { code: '741', name: 'Banco Ribeirão Preto S.A.' },
  { code: '743', name: 'Banco Semear S.A.' },
  { code: '745', name: 'Banco Citibank S.A.' },
  { code: '746', name: 'Banco Modal S.A.' },
  { code: '747', name: 'Banco Rabobank International Brasil S.A.' },
  { code: '748', name: 'Banco Cooperativo Sicredi S.A.' },
  { code: '751', name: 'Scotiabank Brasil S.A. Banco Múltiplo' },
  { code: '752', name: 'Banco BNP Paribas Brasil S.A.' },
  { code: '753', name: 'Novo Banco Continental S.A. – Banco Múltiplo' },
  { code: '754', name: 'Banco Sistema S.A.' },
  { code: '755', name: 'Bank of America Merrill Lynch Banco Múltiplo S.A.' },
  { code: '756', name: 'Banco Cooperativo Sicoob S.A. – Banco Sicoob' },
  { code: '757', name: 'Banco Keb Hana do Brasil S.A.' },
].sort((a, b) => a.name.localeCompare(b.name, 'pt-BR'));

export const BRAZILIAN_BANK_OPTIONS = BRAZILIAN_BANKS.map((bank) => ({
  value: bank.code,
  label: `${bank.code} — ${bank.name}`,
  name: bank.name,
}));

export function findBankByCode(code: string | null | undefined): BrazilianBank | undefined {
  if (!code) {
    return undefined;
  }

  const normalized = code.trim().padStart(3, '0');

  return BRAZILIAN_BANKS.find((bank) => bank.code === normalized || bank.code === code.trim());
}
